package logsEvents

const (
	NEW_GAME            = "NEW_GAME"
	ADMIN_BROADCAST     = "ADMIN_BROADCAST"
	PLAYER_CONNECTED    = "PLAYER_CONNECTED"
	PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"
	PLAYER_REVIVED      = "PLAYER_REVIVED"
	PLAYER_WOUNDED      = "PLAYER_WOUNDED"
	PLAYER_DIED         = "PLAYER_DIED"
	PLAYER_POSSESS      = "PLAYER_POSSESS"
	PLAYER_UNPOSSESS    = "PLAYER_UNPOSSESS"
	PLAYER_DAMAGED      = "PLAYER_DAMAGED"
	PLAYER_SUICIDE      = "PLAYER_SUICIDE"
	PLAYER_QUEUED       = "PLAYER_QUEUED"
	DEPLOYABLE_DAMAGED  = "DEPLOYABLE_DAMAGED"
	ROUND_ENDED         = "ROUND_ENDED"
	ROUND_TICKETS       = "ROUND_TICKETS"
	ROUND_WINNER        = "ROUND_WINNER"
	SQUAD_CREATED       = "SQUAD_CREATED"
	VEHICLE_DAMAGED     = "VEHICLE_DAMAGED"
	SERVER_TICKRATE     = "SERVER_TICKRATE"
	EXPLOSIVE_DAMAGED   = "EXPLOSIVE_DAMAGED"

	RECONNECTING = "reconnecting"
	CONNECTED    = "connected"
	CLOSE        = "close"
	ERROR        = "error"
)
